### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.python.keras.applications'

### ISSUE THREAD

**Issue by Ek-Ram** [BbChip0103/keras_application_3D#3]
I got this error while using in google colab : [/usr/local/lib/python3.10/dist-packages/keras_applications_3d/vgg16.py](https://localhost:8080/#) in <module>
     21 
     22 from tensorflow.keras import backend
---> 23 from tensorflow.python.keras.applications import imagenet_utils
     24 from tensorflow.python.keras.engine import training
     25 from tensorflow.python.keras.layers import VersionAwareLayers

ModuleNotFoundError: No module named 'tensorflow.python.keras.applications'

**Comment by BbChip0103** [comment]
Hi, @Ek-Ram
Thank you for reporting the issue.

I haven't been cared to this project for a while, and a lot of code base has changed in the meantime.
I will update my code ASAP.

**Comment by BbChip0103** [comment]
Migration is completed.
Please try again.

thank you.

**Comment by Ek-Ram** [comment]
Great, 
Thank you
